def props = [:]
pipeline {
    agent {
        yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: alpine-docker
            image: 'dylanmehmedovic/apline-docker:latest'
            command:
            - cat
            tty: true
            '''
    }
    triggers {
        eventTrigger jmespathQuery()
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }
    stages {
        stage('declare properties file'){
            script {
                container('<container name>') {
                    props = readProperties(file: 'build.properties')
                }
            }
        }
        stage('build') {
            sh 'mvn -B -DskipTests clean package'
        }
        stage('unit tests') {
            sh 'mvn test'
        }
        stage('prepare environment') {
            sh 'terraform apply -auto-approve'
        }
        stage('deploy stage') {
            sh 'echo "scp build artifact to EC2 Apache Tomcat Server, then redtart apache service"'
        }
    }
}
